name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn run typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn run lint
  
