name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  runs-on: ubuntu-latest

jobs:
  typecheck:
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run typecheck
  lint:
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run lint
